require 'erb'
require 'sinatra'

set :port, 9876

def dump(request)
  <<~HEREDOC
    <h2>Request Parameters</h2>
    <pre>
    request.url=#{request.url}
    request.fullpath=#{request.fullpath}
    request.path_info=#{request.path_info}
    request.params=#{request.params.map { |k, v| "\n  #{k}=#{v}" }.join(' ')}

    HTTP_USER_AGENT=#{request.env['HTTP_USER_AGENT']}
    </pre>
  HEREDOC
end

get '/' do
  content_type 'html'
  erb :index
end

get '/dump' do
  <<~HEREDOC
    <title>SinatraRequestExplorer dump</title>
    <h2>Get Method</h2>
    <p>Generated by the get /dump handler.</p>
    <p>Go to <a href="/">Root</a>.</p>
    #{dump request}
  HEREDOC
end

post '/dump' do
  <<~HEREDOC
    <title>SinatraRequestExplorer dump</title>
    <h2>Post Method</h2>
    <p>Generated by the post /dump handler.</p>
    <p>Go to <a href="/">Root</a>.</p>
    #{dump request}
  HEREDOC
end
