require 'erb'
require 'sinatra'

set :port, 9876

def dump(request)
  <<~HEREDOC
  <h2>Request Parameters</h2>
  <pre>
  request.url=#{request.url}
  request.fullpath=#{request.fullpath}
  request.path_info=#{request.path_info}

  HTTP_USER_AGENT=#{request.env['HTTP_USER_AGENT']}
  </pre>
  HEREDOC
end

get '/' do
  content_type 'html'
  erb :index
end

get '/getTest' do
  <<~HEREDOC
    <title>SimpleSample getTest</title>
    <h2>Get Test</h2>
    <p>Generated by the getTest handler.</p>
    <p>Go to <a href="/">Root</a>.</p>
    #{dump request}
  HEREDOC
end
